apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nextepc-pgw-deployment
spec:
  selector:
    matchLabels:
      app: nextepc-pgw
  replicas: 1
  template:
    metadata:
      labels:
        app: nextepc-pgw
    spec:
      containers:      
      - name: nextepc-pgw-container
        image: cewuandy/nextepc-base
        securityContext:
          privileged: true
        command: ["/bin/sh"]
        args: ["-c", "/root/nextepc/setup-pgwtun.sh && sh -c /root/nextepc/nextepc-pgwd"]
        volumeMounts:
          - mountPath: /dev/net/tun
            name: tun-volume
          - mountPath: /dev/bus
            name: bus-volume
          - name: nextepc-conf
            mountPath: /root/nextepc/install/etc/nextepc/
      initContainers:
      - name: init-network-client
        image: sdnvortex/network-controller:v0.4.9
        command: ["/go/bin/client"]
        args: ["-s=unix:///tmp/vortex.sock", "-b=br0", "-n=eth1", "-i=192.188.2.5/24"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
      - name: tun-volume
        hostPath:
          path: /dev/net/tun
      - name: bus-volume
        hostPath:
          path: /dev/bus
      - name: nextepc-conf
        configMap:
          name: nextepc-config
