apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nextepc-hss-deployment
spec:
  selector:
    matchLabels:
      app: nextepc-hss
  replicas: 1
  template:
    metadata:
      labels:
        app: nextepc-hss
    spec:
      containers:      
      - name: myapp-container
        image: cewuandy/nextepc-base
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "/root/nextepc/nextepc-hssd"]
        volumeMounts:
        - name: nextepc-conf
          mountPath: /root/nextepc/install/etc/nextepc/
      initContainers:
      - name: init-network-client
        image: sdnvortex/network-controller:v0.4.9
        command: ["/go/bin/client"]
        args: ["-s=unix:///tmp/vortex.sock", "-b=br0", "-n=eth1", "-i=192.188.2.3/24"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
      - name: nextepc-conf
        configMap:
          name: nextepc-config
